"""empty message

Revision ID: 117c7c056427
Revises: 80c6c3c8593d
Create Date: 2024-03-15 13:24:31.897239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117c7c056427'
down_revision = '80c6c3c8593d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint('properties_username_key', type_='unique')
        batch_op.drop_column('username')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('properties_username_key', ['username'])

    # ### end Alembic commands ###
